apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application1
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/saaj562/argocd-app-config.git
    targetRevision: main
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
